POST http://localhost:8080/users
Content-Type: application/json

{
  "first_name": "Andrey",
  "last_name": "Tabakov",
  "email": "komdosh@yandex.ru"
}

###

GET http://localhost:8080/users/133
Content-Type: application/json
