POST http://localhost:8081/users
Content-Type: application/json
X-Public: false

{
  "first_name": "Andrey",
  "last_name": "Tabakov",
  "email": "komdosh@yandex1.ru",
  "password": "123"
}

###

GET http://localhost:8081/users/13?access_token=31e31d2fdd27b81ac7e8ad525a5bb0c35824af0c
Content-Type: application/json
X-Public: true

###

GET http://localhost:8081/users/13
Content-Type: application/json
X-Public: true

###

GET http://localhost:8081/users/13
Content-Type: application/json
X-Public: false

###

PUT http://localhost:8081/users/13
Content-Type: application/json
X-Public: false

{
  "id": 13,
  "first_name": "Andrey",
  "last_name": "Tabakov",
  "email": "komdosh@yandex.ru",
  "date_created": "12-08-2020T080:33:46Z"
}

###

GET http://localhost:8081/internal/users/search?status=active
Content-Type: application/json
X-Public: false

###

POST http://localhost:8081/users/login
Content-Type: application/json
X-Public: false

{
  "email": "komdosh@yandex.ru",
  "password": "0"
}
